[package]
name = "queen-sweep-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
queen-sweep-core = { path = "../queen-sweep-core" }
js-sys = "0.3.81"
