[project]
name = "queen-sweep-python"
version = "0.1.0"
description = "An AI agent that autonomously solves the LinkedIn Queens puzzle"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colorama>=0.4.6",
    "numpy>=2.3.3",
    "pydantic>=2.11.10",
]
